name: travel_aliga
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.0+2
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^6.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  iconify_flutter: ^0.0.4
  internet_connection_checker: ^0.0.1+4
  jwt_decoder: ^2.0.1
  lottie: ^1.4.2
  razorpay_flutter: ^1.3.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/
    - asset/no-connection-internet.json
